name: Mi primer pipeline

on:
  push:

jobs:
  primer-trabajo:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4        #Sin este paso, la máquina no tendría tu proyecto.

      - name: Configurar Python          #sirve para preparar Python
        uses: actions/setup-python@v5    #uses significa que vamos a reutilizar una acción de GitHub, en este caso la acción setup-python.
        with:
          python-version: '3.13'

      - name: Comprobar versión de Python               #queremos comprobar que realmente se ha configurado.
        run: python --version

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Analizar con Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs               #Analiza los archivos del proyecto.
          scan-ref: .                 #el punto significa la carpeta actual, es decir, el proyecto.
          scanners: vuln              #Utiliza el escáner de vulnerabilidades.
          format: table
          exit-code: '0'              #Cuando termines, devuelve el código de salida 0.
          ignore-unfixed: true

      - name: Analizar dependencias con OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Proyecto2-DevSecOps"                  #da un nombre al proyecto dentro del informe que generará Dependency-Check.
          path: .                                         #directorio actual
          format: "HTML"                                  #Genera el informe en formato HTML
          out: reports                                    #escribe en reports.

      - name: Subir informe Dependency-Check              #sube el informe generado.
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report                   #nombre del artefacto que se subirá.
          path: reports                                   #Sube la carpeta reports

      - name: Mostrar un mensaje
        run: echo "Hola desde GitHub Actions"
      